# =============================================================================
# phase1_genesys_zu.xdc
#
# Physical constraints for Phase 1 (Pmod I2S2 loopback).
# Board:  Digilent Genesys ZU-3EG  (board_part digilentinc.com:gzu_3eg:part0:1.0)
# Device: xczu3eg-sfvc784-1-e  (Zynq UltraScale+ MPSoC)
#
# Ported from constraints/archive/phase1_arty_z7.xdc. Pin assignments taken
# from Digilent's official Genesys-ZU-3EG master XDC:
#   https://github.com/Digilent/digilent-xdc  (Genesys-ZU-3EG-Master.xdc)
#
# PORT NAMING: the RTL port prefix matches the board silkscreen -- the single
# Phase 1 I2S2 module is on Pmod JB (jb_* ports). The ZU-3EG's Pmod JA is the
# analog XADC Pmod (LVCMOS18, RC-filtered) and cannot carry the 3.3 V I2S2, so
# the digital Pmod JB is used.
#
# CLOCK NOTE: unlike the Arty Z7 (125 MHz single-ended LVCMOS33 on H16), the
# ZU-3EG's PL reference is a 25 MHz LVCMOS18 clock on E12, generated by the
# on-board Ethernet PHY. The Clocking Wizard input frequency is therefore
# 25.000 MHz (set in scripts/create_project.tcl); the 12.288 MHz audio MCLK it
# produces -- and everything downstream (SCLK divider, ODDR forwarding, codec
# timing) -- is unchanged from the Arty build.
# =============================================================================

# ------ PL system clock: 25 MHz on E12 (from Ethernet PHY) ------
# LVCMOS18 (bank is 1.8 V) -- do NOT reuse the Arty's LVCMOS33 here.
set_property -dict { PACKAGE_PIN E12  IOSTANDARD LVCMOS18 } [get_ports { sysclk }]

# Primary input clock (25 MHz = 40 ns). REQUIRED: the Clocking Wizard derives
# mclk (12.288 MHz) from this. The ZU-3EG's HDIO input pin does not auto-create
# it (the Arty's clock-capable pin did), so without this line the MMCM output
# clock is never defined and downstream clocks lose their master.
create_clock -name sysclk -period 40.000 [get_ports sysclk]

# HDIO clock-route override: E12 is on a HIGH_DENSITY bank with no dedicated
# clock route to the CMT, so the IOB->BUFG->MMCM chain can't stay within one
# clock region and the IO clock placer fails. Allow the MMCM input clock to
# reach the CMT over a non-region-local column route (acceptable: the MMCM
# reconditions the clock, 12.288 MHz has ~81 ns margin). Long-term, source the
# PL clock from the PS instead of this HDIO pin.
set_property CLOCK_DEDICATED_ROUTE ANY_CMT_COLUMN [get_nets u_mmcm/inst/clk_in1_clk_wiz_audio]

# ------ Pmod JB: Pmod I2S2  (jb_* ports) ------

# DAC side (CS4344 "Line Out") - Pmod pins 1..4, JB bottom row
set_property -dict { PACKAGE_PIN AE13 IOSTANDARD LVCMOS33 } [get_ports { jb_da_mclk }] ;# JB1  (Pmod pin 1)  D/A MCLK
set_property -dict { PACKAGE_PIN AG14 IOSTANDARD LVCMOS33 } [get_ports { jb_da_lrck }] ;# JB2  (Pmod pin 2)  D/A LRCK
set_property -dict { PACKAGE_PIN AH14 IOSTANDARD LVCMOS33 } [get_ports { jb_da_sclk }] ;# JB3  (Pmod pin 3)  D/A SCLK
set_property -dict { PACKAGE_PIN AG13 IOSTANDARD LVCMOS33 } [get_ports { jb_da_sdin }] ;# JB4  (Pmod pin 4)  D/A SDIN

# ADC side (CS5343 "Line In") - Pmod pins 7..10, JB top row
set_property -dict { PACKAGE_PIN AE14 IOSTANDARD LVCMOS33 } [get_ports { jb_ad_mclk  }] ;# JB7  (Pmod pin 7)  A/D MCLK
set_property -dict { PACKAGE_PIN AF13 IOSTANDARD LVCMOS33 } [get_ports { jb_ad_lrck  }] ;# JB8  (Pmod pin 8)  A/D LRCK
set_property -dict { PACKAGE_PIN AE15 IOSTANDARD LVCMOS33 } [get_ports { jb_ad_sclk  }] ;# JB9  (Pmod pin 9)  A/D SCLK
set_property -dict { PACKAGE_PIN AH13 IOSTANDARD LVCMOS33 } [get_ports { jb_ad_sdout }] ;# JB10 (Pmod pin 10) A/D SDOUT
