# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Alex/Desktop/FPGAmixer_main/FPGAmixer/vivado_project/FPGAmixer.srcs/sources_1/ip/clk_wiz_audio/clk_wiz_audio.xci
# IP: The module: 'clk_wiz_audio' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Alex/Desktop/FPGAmixer_main/FPGAmixer/vivado_project/FPGAmixer.gen/sources_1/ip/clk_wiz_audio/clk_wiz_audio_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_audio'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Alex/Desktop/FPGAmixer_main/FPGAmixer/vivado_project/FPGAmixer.gen/sources_1/ip/clk_wiz_audio/clk_wiz_audio.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_audio'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Alex/Desktop/FPGAmixer_main/FPGAmixer/vivado_project/FPGAmixer.gen/sources_1/ip/clk_wiz_audio/clk_wiz_audio_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_audio'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Alex/Desktop/FPGAmixer_main/FPGAmixer/vivado_project/FPGAmixer.srcs/sources_1/ip/clk_wiz_audio/clk_wiz_audio.xci
# IP: The module: 'clk_wiz_audio' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Alex/Desktop/FPGAmixer_main/FPGAmixer/vivado_project/FPGAmixer.gen/sources_1/ip/clk_wiz_audio/clk_wiz_audio_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_audio'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Alex/Desktop/FPGAmixer_main/FPGAmixer/vivado_project/FPGAmixer.gen/sources_1/ip/clk_wiz_audio/clk_wiz_audio.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_audio'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Alex/Desktop/FPGAmixer_main/FPGAmixer/vivado_project/FPGAmixer.gen/sources_1/ip/clk_wiz_audio/clk_wiz_audio_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_audio'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
