// -----------------------------------------------------------------------------
// clk_wiz_audio_stub.sv   (SIMULATION ONLY -- never synthesized)
//
// Behavioral stand-in for the Vivado Clocking Wizard IP `clk_wiz_audio`, so
// phase3_top can be elaborated and simulated in a plain command-line simulator
// that has no Xilinx IP. Generates a free-running ~12.288 MHz clk_out1 and
// asserts `locked` after a short delay. Frequency accuracy is irrelevant in
// sim -- only the ratios produced by i2s_clock_divider matter.
//
// The real IP is regenerated by scripts/create_project.tcl for hardware builds;
// this file must be kept OUT of the synthesis fileset.
// -----------------------------------------------------------------------------
`timescale 1ns / 1ps

module clk_wiz_audio (
    input  logic clk_in1,
    input  logic reset,
    output logic clk_out1,
    output logic locked
);
    // ~12.288 MHz -> period 81.38 ns -> half 40.69 ns
    localparam real HALF_NS = 40.69;

    logic clk = 1'b0;
    always #(HALF_NS) clk = ~clk;
    assign clk_out1 = clk;

    initial begin
        locked = 1'b0;
        #1000;              // pretend the PLL takes ~1 us to lock
        locked = 1'b1;
    end
    // Model reset dropping lock.
    always @(posedge reset) locked = 1'b0;

endmodule
